#!/usr/bin/python3

def serve(dirname=None):
    """
    Register as a zeroconf/Bonjour service and serves files in dirname directory
    if dirname is missing, it serves files from the current working directory.
    """

def list_hosts():
    """
    Scans the network for LANShare hosts and prints them to stdout.
    """

def list_files(hostname):
    """
    Asks a host for a list of it's shared files and prints them to stdout.
    """

def get_file(hostname, filename, output=None):
    """
    Gets a filename from hostname and save it as output.
    """

def parse_options():
    """
    Read the command line options and call the related function.
    + Serve files
    + List available hosts
    + List files on a host
    + Get a file from a host
    """

if __name__ == "__main__":
    parse_options()
