#!/usr/bin/python3
import os, sys, socket, socketserver
from os.path import isfile, join
from zeroconf import ServiceInfo, ServiceBrowser, ServiceStateChange, Zeroconf
from time import sleep

DirName = None

def print_hostnames(zeroconf, service_type, name, state_change):
    """
    Prints the hostname to stdout
    """
    if state_change is ServiceStateChange.Added:
        hostname = name.split('.')
        print(hostname[0])

def list_dir(dirname):
    filelist = ""
    if dirname is None:
        dirname = os.getcwd()
    for file in os.listdir(dirname):
        if isfile(file):
            filelist += file
            filelist += "\n"

    return filelist

class ShareHandler(socketserver.BaseRequestHandler):

    def handle(self):
        self.command = self.request.recv(1024).strip()
        if self.command == b'LIST':
            list_str = list_dir(DirName)
            self.request.sendall(str.encode(list_str))
        elif self.command == b'GET':
            relf.request.sendall(b'2 Sending file...')
        else:
            self.request.sendall(b'3 Unknown command')

def serve(dirname=None):
    """
    Register as a zeroconf/Bonjour service and serves files in dirname directory
    if dirname is missing, it serves files from the current working directory.
    """
    # Register with the Zeroconf/Bonjour daemon
    hostname = socket.gethostname()
    ip_addr = socket.gethostbyname(hostname)
    # Should ask the OS for a port binding to 0
    port = 10108
    desc = {'version': '0-alpha'}

    info = ServiceInfo("_lanshare._tcp.local.",
                "{0}._lanshare._tcp.local.".format(hostname),
                socket.inet_aton(ip_addr),
                port, 0, 0,
                desc,
                "{0}.local.".format(hostname))

    zeroconf = Zeroconf()
    print("Press Ctrl-C to stop sharing...")
    zeroconf.register_service(info)

    DirName = dirname
    # Here is where we will serve the files
    try:
        server = socketserver.TCPServer((hostname, port), ShareHandler)
        server.serve_forever()
    except KeyboardInterrupt:
        # Stop on Ctrl+C
        pass
    finally:
        # De-register the service
        zeroconf.unregister_service(info)
        zeroconf.close()

def list_hosts():
    """
    Scans the network for LANShare hosts and prints them to stdout.
    """
    zeroconf = Zeroconf()
    browser = ServiceBrowser(zeroconf,
                    '_lanshare._tcp.local.',
                    handlers=[print_hostnames])

    sleep(0.5)
    zeroconf.close()

def get_hostinfo(hostname):
    hosts = []
    host_info = None

    def get_hostnames(zeroconf, service_type, name, state_change):
        if state_change is ServiceStateChange.Added:
            hostname = name.split('.')
            host = zeroconf.get_service_info(service_type, name)
            hosts.append(host)

    zeroconf = Zeroconf()
    browser = ServiceBrowser(zeroconf,
                    '_lanshare._tcp.local.',
                   handlers=[get_hostnames])

    sleep(0.5)
    zeroconf.close()

    fqdn = '{0}.local.'.format(hostname)

    for host in hosts:
        if host.server == fqdn:
            host_info = host

    return host_info

def list_files(hostname):
    """
    Asks a host for a list of it's shared files and prints them to stdout.
    """
    host = get_hostinfo(hostname)

    if host is None:
        print("Couldn't find host {0}".format(hostname))
        return

    # Create a socket (SOCK_STREAM means a TCP socket)
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

    try:
         # Connect to server and request list of files
        sock.connect((socket.inet_ntoa(host.address), host.port))
        sock.sendall(b"LIST")

        # Receive data from the server and shut down
        received = str(sock.recv(1024), "utf-8")
    finally:
        sock.close()

    print(received)

def get_file(hostname, filename, output=None):
    """
    Gets a filename from hostname and save it as output.
    """
    print("Getting file {0} from {1}".format(filename, hostname))

def usage():
    """
    Print the help message
    """
    print("lanshare help...")

def parse_options(args):
    """
    Read the command line options and call the related function.
    + Serve files
    + List available hosts
    + List files on a host
    + Get a file from a host
    """
    if len(args) == 1:
        list_hosts()
    elif args[1] == "-S":
        if len(sys.argv) > 2:
            serve(args[2])
        else:
            serve()
    elif args[1] == "-h":
        usage()
    elif len(args) == 2:
        list_files(args[1])
    else:
        get_file(args[1], args[2])


if __name__ == "__main__":
    parse_options(sys.argv)

